// <auto-generated />
namespace WareHouseLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changedDBSchemaToModel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedDBSchemaToModel2));
        
        string IMigrationMetadata.Id
        {
            get { return "202004122051298_changedDBSchemaToModel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
